# AMD64_AARCH64_ARCH is mandatory, passed in from build.sh
ARG AMD64_AARCH64_ARCH

# Some of the tools use `arm64` instead of `aarch64`
ARG AMD64_ARM64_ARCH

# Subscription manager configuration is mandatory, passed in via environment
ARG SUBSCRIPTION_MANAGER_ORG
ARG SUBSCRIPTION_MANAGER_KEY

# The origin-cli image is provided as amd64 but contains multiple binaries for different architectures
FROM --platform=linux/amd64 quay.io/openshift/origin-cli-artifacts:latest as openshift-cli

FROM --platform=linux/${AMD64_AARCH64_ARCH} registry.redhat.io/rhel9-4-els/rhel:9.4

# Pass args into the build stage
ARG AMD64_AARCH64_ARCH
ARG AMD64_ARM64_ARCH
ARG SUBSCRIPTION_MANAGER_ORG
ARG SUBSCRIPTION_MANAGER_KEY

# Explicitly set root user
USER root

# Explicitly set the path to include extra paths for golang and rust
ENV PATH "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/go/bin:/root/.cargo/bin"

# Copy the oc binary from the cli image
COPY --from=openshift-cli /usr/share/openshift/linux_${AMD64_ARM64_ARCH}/oc.rhel9 /usr/local/bin/oc
RUN chmod +x /usr/local/bin/oc

# Install jq from github
RUN curl -L -o /usr/local/bin/jq https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-${AMD64_ARM64_ARCH} && \
    chmod +x /usr/local/bin/jq

# Install yq from github
RUN curl -L -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_${AMD64_ARM64_ARCH} && \
    chmod +x /usr/local/bin/yq

# Install kustomize from github
RUN curl -s -o /tmp/install_kustomize.sh "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" && \
    chmod +x /tmp/install_kustomize.sh && \
    /tmp/install_kustomize.sh /usr/local/bin && \
    chmod +x /usr/local/bin/kustomize && \
    rm /tmp/install_kustomize.sh

# Configure subscription for RHEL packages
RUN subscription-manager register --org "${SUBSCRIPTION_MANAGER_ORG}" --activationkey "${SUBSCRIPTION_MANAGER_KEY}"

# Install EPEL for extra packages
RUN yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y

# We will need basically everything in this group eventually
RUN yum groupinstall 'Development Tools' -y

# Need to enable nodejs module to get a reasonably current version
RUN yum module enable nodejs:20 -y

# Also install some specific packages
RUN yum install \
        cargo \
        container-tools \
        golang \
        nodejs \
        moreutils \
        pinentry \
        rust \
        wget \
        zsh \
        -y

# Copy entrypoint
COPY entrypoint.sh /root/entrypoint.sh
ENTRYPOINT ["/root/entrypoint.sh"]
